services:
  - type: web
    name: telemed-ai-backend
    env: python
    plan: free
    pythonVersion: "3.11"
    buildCommand: |
      cd backend && 
      pip install --upgrade pip setuptools wheel && 
      pip install --prefer-binary --no-cache-dir -r requirements.txt
    startCommand: "cd backend && python -m uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USER
        value: your-email@gmail.com
      - key: SMTP_PASS
        value: your-app-password
      - key: SMTP_FROM
        value: noreply@telemed.com
      - key: DEFAULT_APPOINTMENT_EMAIL
        value: admin@telemed.com
      - key: OCR_SERVICE_URL
        value: http://localhost:5000
